
--EJERCICIO 1
SELECT MIEMBRO.ID, MIEMBRO.ID_VECINO, VECINO.NOMBRE, MIEMBRO.PERIODO_INICIO, MIEMBRO.PERIODO_FIN from MIEMBRO INNER JOIN VECINO on MIEMBRO.ID_VECINO = VECINO.ID WHERE Miembro.id_comite = 1;
--EJERCICIO 3
SELECT ESTADO_DENUNCIA.ESTADO, COUNT(DENUNCIA.ID_ESTADO) FROM ESTADO_DENUNCIA INNER JOIN DENUNCIA ON ESTADO_DENUNCIA.ID = DENUNCIA.ID_ESTADO WHERE ESTADO_DENUNCIA.ID = DENUNCIA.ID_ESTADO GROUP BY DENUNCIA.ID_ESTADO, ESTADO_DENUNCIA.ESTADO